health:
  check:
    # URI to ping
    uri:
    # API-Key used to authenticate URI to ping
    api-key:
    # Delay between each ping (in milliseconds)
    delay:
    # Expected string response
    response:
  data:
    mongodb:
      # MongoDB cluster URI
      uri:
      # MongoDB database name
      database:
spring:
  # SMTP configuration
  mail:
    host:
    port:
    username:
    password:
    from:
    to:
    subject:
