health:
  check:
    uri: ${HC_URI}
    delay: ${HC_DELAY}
    response: ${HC_RESPONSE}

spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PWD}
    from: ${MAIL_FROM}
    to: ${MAIL_TO}
    subject: ${MAIL_SUBJECT}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          port: 587
          ssl:
            trust: smtp.office365.com
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

management:
  metrics:
    export:
      influx:
        uri: ${INFLUX_URI}
        org: ${INFLUX_ORG}
        bucket: ${INFLUX_BUCKET}
        token: ${INFLUX_TOKEN}
        step: ${INFLUX_STEP}
    tags:
      application: ${INFLUX_APPLICATION}

logging:
  level:
    root: ${LOGGING_LEVEL}