<!DOCTYPE html>
<html lang="fr-FR">
<head>
    <title>HealthChecker Connection $status$</title>
    <style>
        body {
            font-family: Calibri Light, Helvetica, Arial, sans-serif;
            font-size: 11pt;
        }
    </style>
</head>

<body>
<p>
    Hello,
</p>
<p>
    Connection <code>$status$</code>:
</p>
<table>
    <tr>
        <td>Host</td>
        <td><code>$host$</code></td>
    </tr>
    <tr>
        <td>Timestamp</td>
        <td><code>$timestamp$</code></td>
    </tr>
    <tr>
        <td>Status</td>
        <td><code>$httpStatus$</code></td>
    </tr>
</table>
<p>
    Message:
</p>
<p style="border: solid 1px black; padding: 10px">
    <code>$message$</code>
</p>
<p>
    Regards,
</p>
<p>
    <b>RadixHomeWork</b> | HealthChecker<br/>
    <a href="mailto:radixhomework@outlook.com">radixhomework@outlook.com</a><br/>
    <a href="https://github.com/radixhomework/healthchecker">https://github.com/radixhomework/healthchecker</a>
</p>
</body>
</html>