name: Feature and Push-Request Build

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Maven Build
        run: mvn spring-boot:build-image \
          -Dspring-boot.build-image.docker.publishRegistry.url="${{ secrets.DOCKER_HUB_RHW_URL }}" \
          -Dspring-boot.build-image.docker.publishRegistry.username="${{ secrets.DOCKER_HUB_RHW_USERNAME }}" \
          -Dspring-boot.build-image.docker.publishRegistry.token="${{ secrets.DOCKER_HUB_RHW_TOKEN }}"
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_RHW_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_RHW_TOKEN }}
      #- name: Get Image List
      #  run: docker image ls -a
      #- name: Build and push
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ secrets.DOCKER_HUB_RHW_USERNAME }}/healthchecker:snapshot
